apiVersion: apps/v1
kind: Deployment
metadata:
  name: rancher-deployment
  spec:
    selector:
      matchLabels:
        app: rancher
    replicas: 1
    template:
      metadata:
        labels:
          app: rancher
      spec:
        containers:
        - name: rancher
          image: rancher/rancher:latest
          ports:
          - containerPort: 80
